server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  application:
    name: user-center
  session: # 设置session的过期时间
    timeout: 86400
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${xf.db.host}:3306/${xf.db.database}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${xf.db.username}
    password: ${xf.db.password}
  data:
    redis:
      host: ${xf.redis.host}
      port: 6379
      password: ${xf.redis.password}
      database: 1
  rabbitmq:
    host: ${xf.rabbit.host}
    port: 5672
    username: ${xf.rabbit.username}
    password: ${xf.rabbit.password}
    virtual-host: ${xf.rabbit.vhost}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭驼峰命名，不过直接@TableField(value = "isDelete")这个注解，可以不用管这个  开启的话domain的字段例子：userAccount 会变成 user_account
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config: # 逻辑删除字段会参与查询，但是会被过滤掉
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
ali:
  sms:
    accessKeyId: ${xf.sms.accessKeyId}
    accessKeySecret: ${xf.sms.accessKeySecret}
    signName: ${xf.sms.signName}
    verifyCodeTemplate: ${xf.sms.verifyCodeTemplate}